### PR TITLE
Expose lin_debtrank option to shock_and_solve

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by rht** [comment]
One PEP484 stuff: it is python3-specific, but python2 support is about to be discontinued in less than a year anyway (https://python3statement.org/).

**Comment by marcobardoscia** [comment]
I don't think that those commits should be in the same pull request, they are really about two different things. I don't have particular issues in exposing lin_debtrank option to shock_and_solve. However, I don't see the benefit of annotating only one class. Definitely, it does not seem a good reason to break 2.7 compatibility.

**Comment by rht** [comment]
OK, I removed the PEP484 commit. It was just a small gradual patch.

> Definitely, it does not seem a good reason to break 2.7 compatibility.

Once again, 2.7's EOL is Jan 1 2020.

**Comment by marcobardoscia** [comment]
OK, just one small thing: can we have lines 61-62 conditional on method == 'lin_debtrank'?

**Comment by rht** [comment]
Added. I didn't do it earlier because I thought it would be needed by several other methods.

**Pull request merged**
